### ISSUE TITLE
[BUG] - [DND5e] - cannot interact with item piles created from MIDI enabled items

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-ItemPiles#393] opened 2023-06-28 16:57 UTC
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When I create a stack from an on-screen item (embedded item), it doesn't correctly generate the stack when the MIDI module is active. (but no error is displayed) and the token created for the token is a generic and not a real derivative of the "defult item pile"

**To Reproduce**

https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/a85804f4-865b-4ebd-8a33-1e3d0aea516b

**Setup:**

- Foundry Version: [e.g. 10.303]
- System Version: [e.g. DND5e 2.2.1]
- Item Piles Version: [last]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- midi

**Comment by rinnocenti** [comment] 2023-06-29 01:38
The problem is in new Foundry 10.303. In 10.291 the error not happens

**Comment by Haxxer** [comment] 2023-07-01 14:20
I can't reproduce it at all and I'm on 10.303, DnD5e 2.2.1 and MidiQOL 10.0.49 - what are your Midi settings?

**Comment by rinnocenti** [comment] 2023-07-02 03:36
[fvtt-midi-qol-settings.zip](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/11928637/fvtt-midi-qol-settings.zip)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/8cacbe44-bf99-4c11-b0c2-29c46e400890)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/3178127/86334f4c-7b57-4193-9ad7-de7f206e0559)

**Comment by Haxxer** [comment] 2023-07-02 20:36
This is a bug with MidiQOL:

https://discord.com/channels/915186263609454632/1125061930894229544

**Comment by Haxxer** [comment] 2023-07-17 11:54
Should be fixed as of latest midi qol update, possibly.

**Closed by Haxxer** 2023-07-17 11:54 UTC
Labels: bug
