### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Describe bug here

### ISSUE THREAD

**Issue by V3rotti** [fantasycalendar/FoundryVTT-ItemPiles#396] opened 2023-06-30 07:12 UTC
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
The Default Item Pile Actor seems does not open when placed as a token onto the canvas properly.
If a Pile is created via drag and dropping an item onto the canvas, it will open the character sheet on click. 
The auto-created actor opens the item piles dialog correctly first but only until it gets updated, either by adding an item or simply clicking update item pile without even doing any changes.
trying to enable item piles on the actor again throws an error, stating that the type of actor is incompatible.

**To Reproduce**
reproducable like in the linked video 

**Expected behavior**
simply open the item piles correctly.

**Screenshots**
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/56869989/60256edd-bddb-4adb-99cd-a6bc04da447c

**Setup:**

- Foundry Version: [10.303]
- System Version: [DND5e 2.2.1]
- Item Piles Version: [2.6.16]
- Browser & version [Google Chrome 114.0.5735.199]

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- midiqol
- dae

**Additional context**

**Comment by Haxxer** [comment] 2023-06-30 07:13
Is this a duplicate of https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/393?

**Comment by V3rotti** [comment] 2023-06-30 07:41
yeah i see it might be linked to midiqol - after disabling it the piles open

**Closed** 2023-06-30 07:42 UTC
Labels: bug
