### ISSUE TITLE
[REQUEST] - Automatic Repopulation of Item Piles Merchants via RollTable / Simple Calendar

### ISSUE THREAD

**Issue by PlasticMohawk** [fantasycalendar/FoundryVTT-ItemPiles#352] opened 2023-05-04 20:11 UTC
**Is your feature request related to a problem? Please describe.**

As a GM user of Item Piles (PF2E), I rely in Simple Calendar heavily for programmatic/procedural event generation. I would like to set up Item Piles Merchants which use RollTables to repopulate my town shops on a regular basis. However, I don't always remember to do this randomly, causing my players to think my town shops are perpetually out of stock on the essentials such as Rations and Torches.

**Describe the solution you'd like**

I would like to be able to hook into Simple Calendar to automatically repopulate my shops at a specific in-game time using the assigned RollTable(s), for example:
[IDEAL]
-once per day at a specified time, or
-when the shop opens or closes, or
[NICE TO HAVE]
-x days before a Simple Calendar holiday, or
-when a specified moon is in a specified phase, or
-on a change of months or seasons

I understand that some of the above events may necessitate multiple RollTables to be assigned to an individual Merchant actor, therefore I would expect this to add complication and extra development time to the overall feature request. Therefore, I separated the list into "ideal" and "nice to have".

**Describe alternatives you've considered**

Running a World Script  hooking on Simple Calendar's DateTimeChange hook could accomplish one or both of the ideal items, however (assuming I'm not missing anything) I'm unsure if there's a straightforward Item Piles API function which accomplishes this, and using a World Script based approach would mean I'd need to update the World Script whenever I want to add a new Merchant for whatever reason.

**Additional context**
Thanks for your consideration.

**Comment by Haxxer** [comment] 2023-05-04 20:14
This is already possible. Check the bottom of the merchant configuration.

**Comment by Haxxer** [comment] 2023-05-04 20:39
Duplicate of https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/135 in any case

**Closed** 2023-05-04 20:39 UTC
Labels: enhancement
