### ISSUE TITLE
D&D5e dropping containers also puts the items in the container into the item pile

### ISSUE THREAD

**Issue by Vilify-13** [fantasycalendar/FoundryVTT-ItemPiles#533] opened 2024-02-20 02:07 UTC
**Is your feature request related to a problem? Please describe.**
When dropping a container item(like a backpack or pouch) in the latest update for D&D5e on Foundry, the item will leave an item pile, but any objects inside that container won't transfer with it, and will instead get thrown back into the character sheet of the character that had the container on it.

**Describe the solution you'd like**
When dropping a container in 5e on Foundry, it'd be nice and convenient for not only the container, but each of the container's contents to also be added to the pile instead of added to the character sheet, to make it easy to simulate dropping weight quickly in combat such as doffing a backpack to gain the entirety of their move speed if they're currently weighed down.

**Describe alternatives you've considered**
possibly a checkbox to ask if the player dragging that to a pile if they want to send over items inside the container too

**Additional context**
None i believe is relevant

**Comment by Haxxer** [comment] 2024-02-20 06:32
Dupe of https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/527

**Closed by Haxxer** 2024-02-20 06:32 UTC
Labels: enhancement
