### ISSUE TITLE
[BUG] - settings does not open

### ISSUE THREAD

**Issue by eunaumtenhoid** [fantasycalendar/FoundryVTT-ItemPiles#125] opened 2022-09-09 15:02 UTC
**Describe the bug**
going to the foundry settings and trying to open the ittem piles settings, but it doesn't work on the T20 system

**Setup:**
 - Foundry Version: [e.g. 10.284]
 - System Version: [e.g. t20 1.4.0.2]
 - Item Piles Version: [e.g. 2.0.2]
 - Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment] 2022-09-09 15:03
Item Piles is _not V10 ready_. Closing as intended.

**Closed by Haxxer** 2022-09-09 15:03 UTC
Labels: bug
