### ISSUE TITLE
[BUG] - [DND5e] - Toggle locked/closed

### ISSUE THREAD

**Issue by Markus-blip** [fantasycalendar/FoundryVTT-ItemPiles#604] opened 2024-07-06 00:04 UTC
**Are you on the latest version of Item Piles?**
Yes 

**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
Once the Container is set to Lock or Closed it is impossible to revert the change.

**To Reproduce**
1. Create container
2. Right click to lock and/or close
3. Right click again to unlock or open
4. Right click the third time and see it is still closed/locked

**Expected behavior**
To be able to unlock... i guess

**Setup:**
- Foundry Version: 12 build 328
- System Version:  DND5e 3.2.1
- Item Piles Version: 3.0.6

**Active modules:**
- Item Piles 3.0.6
- libwrapper 1.12.13.1
- socketlib 1.1.0

YT link: https://youtu.be/69Dn2pvtdxM

EDIT: update of socketlib did not work, added YT link to show the problem

**Comment by Haxxer** [comment] 2024-07-11 14:56
Duplicate of https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/607

**Closed by Haxxer** 2024-07-11 14:56 UTC
Labels: bug
