### ISSUE TITLE
[BUG] - [5e] - Merchant custom categories aren't functioning + Better Roll Tables interferes with rolltable formulas

### ISSUE THREAD

**Issue by Janner3D** [fantasycalendar/FoundryVTT-ItemPiles#543] opened 2024-03-10 01:06 UTC
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
In the merchant settings, under "Populated Items" when you add a table, no matter what custom category you assign it to, it only ever resorts to the default categories when you add them items to the merchant's inventory.

In addition, Better Roll Tables interferes with the rolltable forumas when adding items to the merchant--no matter what is put into the roll formula box, it only ever rolls from the table once.

**Expected behavior**
The the items added should be assigned their own custom category, and the roll formulas should roll from the table an accurate number of times.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/35965176/f67c16d1-0bbe-4fae-a76f-70206411066d)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/35965176/65319bd9-3833-4281-adb6-daaa54a2b8be)

**Setup:**

- Foundry Version: 11.315
- System Version: DND5e v3.0.4
- Item Piles Version: 2.8.20
- Browser & version Google Chrome

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment] 2024-03-10 09:25
Duplicate of:
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/530
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/521

**Closed by Haxxer** 2024-03-10 09:25 UTC
Labels: bug
