### ISSUE TITLE
[BUG] - Item piles not working when dropping items to canvas

### ISSUE THREAD

**Issue by TheGreatRedDuke** [fantasycalendar/FoundryVTT-ItemPiles#181] opened 2022-11-04 14:52 UTC
**Describe the bug**
I'm new to Item Piles, so I'm not 100% sure how it is supposed to work/behave, but I can't seem to get it working on my Foundry v10 install. When dropping an item to the canvas, the Item Piles dialog does not appear, double clicking open the pile opens a sheet I don't think is correct, and closing that sheet breaks the item icon and the very token itself. I'm running this in a fresh v10 install (build v288) using the Starfinder game system (v0.20.3). The only modules running are: Item Piles, socketlib, libwrapper, and Advanced Macros. I've verified they are all running their lates versions. No console errors are produced. I'll include a screen shot of all console messages generated during the described test.

**To Reproduce**

1. Create a new scene (gave it a generic BG image)
2. Open the Equipment Browser
3. Dragged an item from the Equipment Browser to the game canvas (no Item Piles dialog appears)
4. Double click the item to open sheet (I don't think this is the correct sheet)
5. Close the sheet (icon breaks)
6. Double click to re-open the item (token actor doesn't exist warning appears)

**Expected behavior**
I expected the Item Piled dialog to appear then I dropped the item initially, and I expected the sheet that opens when double clicking to be an Item piles sheet.

**Screenshots**
![image-01](https://user-images.githubusercontent.com/78890368/200004948-d2fbde35-57a4-4225-88b7-4f1c4c0b221b.jpg)
![image-02](https://user-images.githubusercontent.com/78890368/200004951-8aac6e6a-6feb-4dcd-ba02-ab511ada1175.jpg)
![image-03](https://user-images.githubusercontent.com/78890368/200004954-546e1364-6240-40f0-beeb-4a8d8e61b453.jpg)
![image-04](https://user-images.githubusercontent.com/78890368/200004957-ed164aa1-57e0-4a55-a05f-9d8d7c2198c7.jpg)
![image-05](https://user-images.githubusercontent.com/78890368/200004959-ac341b75-224a-435c-925e-763259a2e848.jpg)

**Setup:**
 - Foundry Version: v10.288
 - System Version: sfrpg v0.20.3 (Starfinder)
 - Item Piles Version: v2.2.10
 - Browser & version: Local Foundry install

**Active modules:**
 - Item Piles v2.2.10
 - libwrapper v1.12.10.0
 - socketlib v1.0.12
 - Advanced Macros v1.17.3

**Additional context**
Again, I've never used Item Piles before, so It's very possible I messed something up or didn't configure something maybe? I checked the module setting and re-defaulted everything back to the game system defaults, but it behaves the same. Please let me know if I can provide any additional information.

**Comment by Haxxer** [comment] 2022-11-04 15:00
It appears that system has its own method of representing items on the canvas? Does the same things happen when Item Piles is not active? If so, please do follow up questions in the Starfinder discord server/channel.

**Comment by TheGreatRedDuke** [comment] 2022-11-04 18:51
It does appear to behave the same way without Item Piles enabled. I assume this means the issue is with the game system and not Item Piles?

I'll definitely follow-up in the Starfinder discord channel, but is there something specific I should be asking them? Is there anything technical I should include or point them at in my question?

**Comment by Haxxer** [comment] 2022-11-04 19:46
I would ask them whether it is possible to disable the system's item drop in any way, if there is not, item piles is probably not going to be compatible with Starfinder, at least not the item drop portion of the module.

**Comment by TheGreatRedDuke** [comment] 2022-11-04 20:19
Got it, Thank you!

**Comment by Haxxer** [comment] 2022-11-10 14:58
Closing as it is not a bug with Item Piles.

**Closed by Haxxer** 2022-11-10 14:58 UTC
Labels: bug

**Comment by LebombJames** [comment] 2023-03-11 02:43
The Starfinder system will now defer to item piles over its own look token implementation. PR [#1000](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1000) no less!
