### ISSUE TITLE
[REQUEST] - Display item rarity/level

### ISSUE THREAD

**Issue by Iankid** [fantasycalendar/FoundryVTT-ItemPiles#317] opened 2023-03-26 19:16 UTC
**Is your feature request related to a problem? Please describe.**
Systems like Pathfinder2e with Rarity, or Starfinder with item level, could do with the ability to display that value in the merchant shop.
This is useful for the players information, but also for the GM to quickly determine after rolling from a table, if said item should be in the shop.

**Describe the solution you'd like**
While not limited to. I am hoping to be able to see this in the item buy items section and the populate items section. I'd imagine there could be a setting to direct towards the item's rarity/level value?

**Comment by Haxxer** [comment] 2023-03-26 19:30
Dupe of https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/170

**Closed by Haxxer** 2023-03-26 19:30 UTC
Labels: enhancement
