### ISSUE TITLE
Item Pile enabled state not remaining enabled

### ISSUE THREAD

**Issue by Soundwavesghost** [fantasycalendar/FoundryVTT-ItemPiles#127] opened 2022-09-09 19:05 UTC
**Describe the bug**
When selecting an empty actor or an item bag dragged onto the map the Enabled state does not remain enabled.

**To Reproduce**
1. Create NPC/PC GM controlled
2. Click on 'Configure'
3. Click Enabled and Update
4. Reopen Configure and enabled state not saved.

**Expected behavior**
Enabled state.

**Screenshots**
![image](https://user-images.githubusercontent.com/5963543/189424892-14046559-f555-468a-8790-4c88fff14cea.png)

**Setup:**
 - Foundry Version: v9.280
 - System Version: Fallout2d20 (9.0.5)
 - Item Piles Version: 2.0.2
 - Browser & version: Foundryvtt local engine

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - or any other modules no change when isolated to the above three.

**Additional context**
Item piles prior to the merchantile add-on (Highly excited to hear it was coming), worked well despite not being explicitly supported.

**Comment by Haxxer** [comment] 2022-09-09 19:27
@Soundwavesghost 
Any errors in your console?

**Comment by Soundwavesghost** [comment] 2022-09-09 19:31
Forget to look there but yes.
 DevTools failed to load source map: Could not load content for http://localhost:30000/modules/item-piles/module.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Haxxer** [comment] 2022-09-09 19:32
Hm, unrelated, but could you try to reinstall the module? It won't fix that specific error, but I can't reproduce your issue on my end.

**Comment by Soundwavesghost** [comment] 2022-09-09 19:37
Curious. No change with a wipe of item piles. I'll try reinstalling it and the required support modules. Weird. Tried rolling back to base 2.0.0 and the same console error and no response from item piles now. Always something.

**Comment by Soundwavesghost** [comment] 2022-09-09 19:37
Got a new error after trying to use the module! 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'item')
[Detected 1 package: item-piles]
    at module.js:1264
    at Array.map (<anonymous>)
    at getActorCurrencies (module.js:1254)
    at getActorItems (module.js:1246)
    at updateItemPileData (module.js:1431)
    at Function._updateItemPile (module.js:34774

**Comment by Soundwavesghost** [comment] 2022-09-09 19:38
I think its catching on the currency....

**Comment by Haxxer** [comment] 2022-09-09 19:39
That's a 2.0.0 error, yeah? Try updating again.

**Comment by Soundwavesghost** [comment] 2022-09-09 19:41
Updated to 2.0.2 and tried to drag a item to the map and got al this.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'item')
[Detected 1 package: item-piles]
    at modules/item-piles/module.js:1264
    at Array.map (<anonymous>)
    at getActorCurrencies (modules/item-piles/module.js:1254)
    at getItemPileTokenImage (modules/item-piles/module.js:1342)
    at Function._createItemPile (modules/item-piles/module.js:34667)
    at async Function._dropItems (modules/item-piles/module.js:34606)
module.js:1264 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'item')
[Detected 1 package: item-piles]
    at modules/item-piles/module.js:1264
    at Array.map (<anonymous>)
    at getActorCurrencies (modules/item-piles/module.js:1254)
    at getActorItems (modules/item-piles/module.js:1246)
    at updateItemPileData (modules/item-piles/module.js:1431)
    at modules/item-piles/module.js:34850
    at Object.runWithout (modules/item-piles/module.js:885)
    at modules/item-piles/module.js:34849
    at modules/item-piles/module.js:875
    at common/utils/helpers.mjs:36

**Comment by Soundwavesghost** [comment] 2022-09-09 19:45
Yeah looks like it all breaks at currency.data.item

**Comment by Haxxer** [comment] 2022-09-09 19:48
Probably because your currencies aren't set up correctly. Please ensure the Item Pile settings are all configured.

**Comment by zejefferson** [comment] 2022-09-09 19:50
Hello,

I have the same issue : the Enabled state does not remain enabled.

Here is what I have in the console if it helps : 

`foundry.js:711 Error: This is not a registered game setting
[Detected 3 packages: item-piles, socketlib, lib-wrapper]
    at ClientSettings.get (foundry.js:2707:42)
    at debug (module.js:921:21)
    at ItemPileSocket.initialize (module.js:40037:7)
    at Object.fn (module.js:46819:18)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Object.fn (socketlib.js:22:8)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Game.initialize (foundry.js:7615:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at 🎁libWrapperInit (libWrapper-api.js:796:11)
onError @ foundry.js:711
socketlib.js:205 Uncaught (in promise) SocketlibUnregisteredHandlerError: No socket handler with the name 'updateItemPile' has been registered.
[Detected 2 packages: socketlib, item-piles]
    at SocketlibSocket._resolveFunction (socketlib.js:205:11)
    at SocketlibSocket.executeAsGM (socketlib.js:88:29)
    at ItemPileSocket.executeAsGM (module.js:40041:25)
    at Object.updateItemPile (module.js:40401:27)
    at HTMLFormElement.updateSettings (module.js:43687:9)
    at HTMLFormElement.<anonymous> (module.js:2123:15)
    at HTMLButtonElement.requestSubmit (module.js:43768:10)
`

Thanks!

**Comment by Soundwavesghost** [comment] 2022-09-09 19:50
I'll go over them again.

**Comment by zejefferson** [comment] 2022-09-09 19:55
@Haxxer I am, yes.

**Comment by Haxxer** [comment] 2022-09-09 19:56
Please refer to the ticket "ITEM PILES IS NOT FOUNDRY V10 COMPATIBLE"

**Comment by Soundwavesghost** [comment] 2022-09-09 19:58
Curious I think there is some definition names that aren't linked up in the Fallout module. As I dig it asks for items that are currency but I don't think the currency is an item unto itself just a number defined on the actor sheets.

**Comment by Haxxer** [comment] 2022-09-09 19:58
Click on the text that says "click here"

**Comment by zejefferson** [comment] 2022-09-09 20:00
@Haxxer Got it, sorry I posted here... Acted a bit too fast when I saw the same issue I had in the topic's title. 
Thanks again for your efforts on the module! :)

**Comment by Soundwavesghost** [comment] 2022-09-09 20:03
The main error says its link to your module not finding "currency.data.item" I searched the fallout 2d20 repository for that item and it found "data.currency.caps" in the actor-inventory HTML. It seems to accept the input but then the module settings themselves don't close on the next submit.

**Comment by Haxxer** [comment] 2022-09-09 20:07
Do you have any warnings when you click it? Every input in the system specific settings needs to be filled.

**Comment by Soundwavesghost** [comment] 2022-09-09 20:14
I backed up my games folder and reinstalled. New error but its because I haven't found the path to the item price yet. Pretty sure one of my other modules likely interacted with "caps" or "data.currency" somehow. If you don't close this I'll post which one I found to be problematic. Thanks for the help regardless me and at least one other Fallout2d20 GM LOVE Item piles.

**Comment by Haxxer** [comment] 2022-09-09 20:14
I don't know off hand, but I'll see about adding official support in the next update :)

**Closed by Haxxer** 2022-09-09 20:14 UTC
Labels: bug
