### ISSUE TITLE
[BUG] - [PF1e] - Taking currency doesn't show in the pile itself

### ISSUE THREAD

**Issue by KyleDornez** [fantasycalendar/FoundryVTT-ItemPiles#528] opened 2024-02-18 07:04 UTC
**Are you on the latest version of Item Piles?**
Yes, 2.8.20

**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
Taking currency from the item pile deposits the money correctly, but the pile itself doesn't show that the cash was taken. The amount of gold corrects itself when pile is closed and opened again, but not "live". 

**To Reproduce**
Take an Item Pile, put some gold into it. 
Have a PC interact with an Item Pile - I logged in from player view in the browser to do that
While controlling the PC, take any amount of currency from the Item Pile. 
At this pont amount of currency should go down, but in my case it doesn't. 

**Expected behavior**
The amount of currency in the pile updating itself once the "take" button is clicked, to reflect how much cash is left. 

**Screenshots**

I've recorded a demonstration: https://www.youtube.com/watch?v=bQ883pEcmbM
(good lord, hearing myself always harrowing >.<)

**Setup:**

- Foundry Version: 11.315
- System Version: Pathfinder 1e 9.6
- Item Piles Version: 2.8.20
- Browser & version: Brave v 1.62.165

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- Sorry, there are actually a lot of modules, but I'm not sure that any would actually interfere in this case.

**Comment by Haxxer** [comment] 2024-03-03 11:29
Have you tried with only minimal modules? I cannot reproduce this.

**Comment by Haxxer** [comment] 2024-03-03 11:40
Actually, found the issue, dupe of https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/526.

**Closed by Haxxer** 2024-03-03 11:40 UTC
Labels: bug, question
