### ISSUE TITLE
[BUG] - [WFRP4] - Not working Item piles char

### ISSUE THREAD

**Issue by Mrak7439** [fantasycalendar/FoundryVTT-ItemPiles#289] opened 2023-03-02 23:31 UTC
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
When you drop an item on the map, a "Default item pile" sheet is created. But its settings don't change as the container item doesn't work. If you create a new sheet, the "item saws" settings are not saved in the settings (the Enable checkbox is reset after closing the settings, it is not saved).

**Expected behavior**

**Screenshots**

**Setup:**

- Foundry Version: 10.291
- System Version: [WFRP-4e 6.3.1]
- Item Piles Version: [2.4.17]
- Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

![2](https://user-images.githubusercontent.com/56008304/222587468-c086b8ed-a9f2-4b55-b6ac-7a6857797964.png)
![1](https://user-images.githubusercontent.com/56008304/222587481-9666afb0-3c75-4565-8424-1295e5270a06.png)

**Comment by Haxxer** [comment] 2023-03-05 14:55
I can't reproduce your problem, but I think it is fixed in 2.4.18

**Closed by Haxxer** 2023-03-05 14:55 UTC
Labels: bug
