### ISSUE TITLE
[BUG] - [PF2e] - Hidden items can't be toggled to be visible

### ISSUE THREAD

**Issue by crovaxeve** [fantasycalendar/FoundryVTT-ItemPiles#646] opened 2024-08-29 05:49 UTC
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Toggling a hidden item to visible immediately reverts the item to hidden upon closing the item pile window if using the eye icon, or never updates at all to become visible if unchecking the "Item is Hidden" box in config.

**To Reproduce**

1. Click the slashed out eye icon to toggle an item to be visible.
2. Close the item pile window.
3. Reopen the item pile window.
4. Item has revered to hidden (slashed out eye icon).
5. Same result if using the cog to uncheck  the "Item is Hidden"  box  and Update Item, except the item never becomes visible (eye never becomes unslashed).

**Setup:**

- Foundry Version 12 Stable - Build 331
- System Version: [e.g. Pathfinder Second Edition 6.2.3]
- Item Piles Version: [e.g. 3.1.1]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment] 2024-08-29 05:52
Is this item pile a linked or unlinked actor? And I'm assuming you're talking about merchants?

**Comment by crovaxeve** [comment] 2024-08-29 05:56
Yes, this is for merchant actors.  I'm relatively new to Foundry, by linked or unlinked do you mean linked to a token?  If so, it doesn't update the visibility for either.  If I just have an actor in  the actors list and open it from there, or if I put them on a map as a token and open it from the token to edit, neither will update the item from hidden to visible.  It does seem to update from visible to hidden, but then it will not update back to visible.

**Comment by Haxxer** [comment] 2024-08-29 06:59
I can't reproduce this - is a GM logged in?

**Comment by Haxxer** [comment] 2024-08-30 13:46
Fixed in 3.1.2

**Closed by Haxxer** 2024-08-30 13:46 UTC
Labels: bug
