### ISSUE TITLE
[REQUEST] - Reset all currencies on new item piles

### ISSUE THREAD

**Issue by Deadlander** [fantasycalendar/FoundryVTT-ItemPiles#44] opened 2022-01-28 02:21 UTC
**Is your feature request related to a problem? Please describe.**
For the SWADE System: When NPCs are created, they have 500 currency, which can flood the players with lots of currency that isn't supposed to be there.

**Describe the solution you'd like**
Have an option for the GM to remove the game system currency from the piles without having to create an actor to do it.  When NPCs are created, they have 500 currency, which can flood the players with lots of currency that isn't supposed to be there.

**Describe alternatives you've considered**
Allowing the GM to remove currency/items without using the character sheet.  (Currency does not show up on SWADE NPC sheets).

**Additional context**

**Comment by Haxxer** [comment] 2022-01-28 08:42
Have you looked into whether your default item pile has currency on it? The default item pile is used whenever a player drops an item, and any items or currencies will come across in the item pile token that is created. This is a feature, not a bug.

**Comment by Deadlander** [comment] 2022-02-02 19:32
The SWADE system automatically assigns 500 to NPCs.  One of the recent updates you folks made it possible to remove said currency!

**Comment by Haxxer** [comment] 2022-02-02 19:33
Excellent, closing as fixed.

**Closed by Haxxer** 2022-02-02 19:33 UTC
Labels: enhancement
