### ISSUE TITLE
Unlinking the actor token on an item pile resets the item pile settings when dragging it into the scene.

### ISSUE THREAD

**Issue by MunchoTheCow** [fantasycalendar/FoundryVTT-ItemPiles#451] opened 2023-09-10 17:00 UTC
**Describe the bug**
Unlinking the actor token on an item pile resets the item pile settings when dragging it into the scene.
This means if you set up a treasure chest, with type = container, locked and image path/sounds, all this information is lost on the new token. 
Linking the token to the actor sheet provides the correct behaviour, but this renders the item pile useless for dropping multiple on the scene and then filling with different items...

**To Reproduce**
- Duplicate the default item pile, set up the type to container and enter some image paths.
- Open the actor sheet of the item pile and the default token, select unlink.
- Drag the item pile actor onto the scene, observe the item pile settings on that instance are now reset.

**Expected behavior**
The new token should be unlinked, but preserve the item pile configuration settings set in the actor sheet.

**Setup:**
- Foundry Version: v11, 308
- System Version: DnD5e 2.3.1
- Item Piles Version: 2.7.12

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Comment by MunchoTheCow** [comment] 2023-09-11 14:49
Seems to be related to the start of onPreCreateToken,
foundry.utils.mergeobject seems to be the culprit, and it's nuking the flag data.
Just grabbing the flags off the source object seems to fix the issue.

**Comment by Haxxer** [comment] 2023-09-18 19:37
I can't reproduce this issue on the same versions as you. Could you please submit a video of you reproducing the bug in a fresh world?

**Comment by Haxxer** [comment] 2023-10-01 15:49
Duplicate of #464, fixed in 2.7.15

**Closed by Haxxer** 2023-10-01 15:49 UTC
Labels: bug
