### ISSUE TITLE
[BUG] - [PF2E] - Item Mystification Not Respected in Item Inspect

### ISSUE THREAD

**Issue by nicole-aylin** [fantasycalendar/FoundryVTT-ItemPiles#354] opened 2023-05-08 04:02 UTC
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
Item mystification (native to Pf2e) is not being respected when the Enable Item Inspect (Item Piles option) is enabled. When opening an item, the original item is being showed instead of the expected mystified item.

**To Reproduce**

1. Create an Item Pile in a Pf2e game
2. Go to the Item Piles settings and enable Enable Item Inspect
3. Import an item from the Compendium (or create a new item)
4. Open the item, go to Mystification and change mystification status to "Unidentified"
5. Drag the item into the Item Pile
6. Click the item so it opens up the item window and see that the real info instead of the unidentified info is present

**Expected behavior**

**Screenshots**
This is what the native version shows/what I would expect to see.
<img width="648" alt="Screen Shot 2023-05-08 at 1 57 56 pm" src="https://user-images.githubusercontent.com/47173655/236730802-956bf032-3272-417c-b73d-1a8085ab3376.png">

This is what Item Piles shows:
<img width="695" alt="Screen Shot 2023-05-08 at 1 59 31 pm" src="https://user-images.githubusercontent.com/47173655/236730859-704ae2d3-b0cd-4161-a519-72ae53e01b5d.png">

**Setup:**

- Foundry Version: 10.291
- System Version: Pathfinder 4.11.2
- Item Piles Version: 2.6.11
- Browser & version: Version 112.0.5615.49 

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment] 2023-05-08 12:58
Duplicate of:
https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues/346

**Closed by Haxxer** 2023-05-08 12:58 UTC
Labels: bug
