### ISSUE TITLE
[BUG] - Can not set default item pile setting on DS4

### ISSUE THREAD

**Issue by STBaf** [fantasycalendar/FoundryVTT-ItemPiles#7] opened 2022-01-05 23:35 UTC
When I try to change the Item Pile settings on the Default Item Pile Actor from which piles are duplicated as template you get a error in the javascript console and the pile settings are not updated. Since the pile seem to should be system agnostic I consider this as a bug. This happens in the DS4 / Dungeonslayers 4 system.

**To Reproduce**
1. Install Game system Dungeonslayers 4
2. Install Item Pile Module ;)
3. Start game world with DS4 system
4. Enable only Item Pile module on new world (and depended, for sure)
5. Create Actor

6. Drop Item from Compendium "Gegenstände (GRW)" to new actor
7. Drop Item from actor from page "Inventar" to the ground, create pile
or
6. create Item
7. drop Item to ground, create pile, you get the default pile
8. try to change settings of default pile
9. when pushing update pile button values are not stored, error message on javascript console

**Expected behavior**
Settings of a pile should be change/updateble when module is system agnostic independent from game system

**Javascript console error**
lib.js:148 
 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'update')
[Detected 1 package: item-piles]
    at Module.updateItemPile (lib.js:148)
    at Function._updateItemPile (api.js:1381)
updateItemPile	@	lib.js:148
_updateItemPile	@	api.js:1381
await in _updateItemPile (asynchron)		
_updateObject	@	itemPileConfig.js:149
_onSubmit	@	foundry.js:3822

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version current stable channel release

**Comment by Haxxer** [comment] 2022-01-05 23:39
I can't reproduce this - could you elaborate what you changed on the item pile?

**Comment by STBaf** [comment] 2022-01-05 23:44
If you are online at this moment could you DM me under STB#9841 on Discord ? then I can give you a link to my VTT to test ;)

**Comment by Berytak** [comment] 2022-01-06 09:31
I'm getting the exact seme error but on a DnD5e Game.

![image](https://user-images.githubusercontent.com/85394657/148360816-3ce2f5c3-4287-46ea-b5a0-bb30a15ae567.png)

This happens when I'm trying to change the container settings on the dafault item pile.

![image](https://user-images.githubusercontent.com/85394657/148361033-886170a0-d598-4146-8df7-7814e4850200.png)

 Hitting the "Update Item Pile" button results in this error and the settings are not changed.

**Comment by Haxxer** [comment] 2022-01-06 11:04
I have identified the fault and it will be fixed in 1.0.1

**Closed by Haxxer** 2022-01-06 11:04 UTC
Labels: bug
