### ISSUE TITLE
[BUG] - Images turning to bag pile

### ISSUE THREAD

**Issue by Avitale34** [fantasycalendar/FoundryVTT-ItemPiles#82] opened 2022-03-14 21:47 UTC
**Describe the bug**
I am having an issue with Item Piles, it seems like some of my images for items in piles keep defaulting back to this bag icon after a day or two. I can't seem to figure out a pattern to why some are doing it and some are not all the items in the directory still have their images and the links are not broken when I click on them they are set to icons/svg/item-bag.svg.

**Expected behavior**
Images to stay the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/65961637/158266722-44101eff-0367-4427-870a-e598edc349cf.png)
![image](https://user-images.githubusercontent.com/65961637/158266766-32226be0-22c4-4e5e-afb0-9705589e6bd4.png)

**Setup:**
 - Foundry Version: [e.g. 9.238]
 - System Version: [e.g. DND5e 1.5.7]
 - Item Piles Version: [e.g. 1.0.0]
 - Browser & version [e.g. Google Chrome 98.0.4758.82]

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Haxxer** [comment] 2022-03-14 21:50
I can say with 100% certainty that Item Piles never updates any item images - it does however change the icon of the item pile token, but never their contained items. Are the active modules that you listed there the _only_ modules you have active when this issue appears?

**Comment by colinbate** [comment] 2022-03-17 04:13
I've seen this as well if I create a pile by dragging an item to the scene, and then manually set the pile token image to be another icon.  At this point, if I (or a player) add or remove an item from the pile (or currency) and update it, it reverts to the `item-bag`.

**Comment by Haxxer** [comment] 2022-09-24 23:38
I can't reproduce this in the latest version. Closing as fixed.

**Closed by Haxxer** 2022-09-24 23:38 UTC
Labels: bug
