### ISSUE TITLE
[BUG] - [5e 3.1] - Backpacks do not bring items on move or drop.

### ISSUE THREAD

**Issue by Ikabodo** [fantasycalendar/FoundryVTT-ItemPiles#578] opened 2024-05-21 08:48 UTC
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
No

**Describe the bug**
If you drop items on the ground, or pick them up through the "take" interface. Or in anyway move a backpack from one actor to the next the items inside the backpack do not move with the backpack. Instead they get "dumped" into the main inventory of the actor that had the backpack.

**To Reproduce**
1. Put backpack on actor
2. Put item in backpack
3. Drop backpack on ground or drag to another actor, or pic up from item pile
4. (items in backpack remains)

**Expected behavior**
The items in the backpack should be moved with the backpack when the backpack is moved. (i assume this might be a core 5e thing?)

**Setup:**
- Foundry Version: v11.515
- System Version: DND5e 3.1.2
- Item Piles Version: 2.9.1

**Active modules:**
- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment] 2024-05-21 09:15
Duplicate of #527

**Closed by Haxxer** 2024-05-21 09:15 UTC
Labels: bug
